image: docker:stable
services:
  - docker:dind

stages:
  - build-production
  - deploy-production

before_script:
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:test
  CONTAINER_PROD_IMAGE: $CI_REGISTRY_IMAGE:prod
  #
build-production:
  image: "registry.gitlab.com/max_siz/synergis-api:remotemongo"
  stage: build-production
  #tags:
  #  - exolover-build
  #only:
  #  - master
  script:
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull --build-arg ENV="production" -t $CONTAINER_PROD_IMAGE .
    - docker push $CONTAINER_PROD_IMAGE