image: docker:stable
services:
  - docker:dind

stages:
  - build-production
  - deploy-production

before_script:
  #- docker info
  #- docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

variables:
  #DOCKER_HOST: docker
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:test
  CONTAINER_PROD_IMAGE: $CI_REGISTRY_IMAGE:prod
  #
build-production:
  #image: "registry.gitlab.com/max_siz/synergis-api:remotemongo"
  stage: build-production
  tags:
    - indock
  #only:
  #  - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull --build-arg ENV="production" -t $CONTAINER_PROD_IMAGE .
    - docker push $CONTAINER_PROD_IMAGE
    - export

deploy-production:
  #image: docker:master
  stage: deploy-production
  tags:
    - prod-dpl
  only:
    - master
  variables:
    #DOCKER_HOST: 127.0.0.1:2375
    #DOCKER_HOST: '172.17.0.1'  
    #DOCKER_HOST: 'tcp://95.179.134.166:2375'  
    #DOCKER_HOST: 'unix:///var/run/docker.sock'
  script:
    #- export
    #- ip address
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    #- sudo docker pull $CONTAINER_PROD_IMAGE
    #- docker rm -f $CI_PROJECT_NAME 2>/dev/null || true    
    - docker-compose up -d